renamed border_width to  segment_border_width to avoid conflict with  Appcomact libs
Error: Attribute "border_width" has already been defined
exampleapp/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.0/res/values/values.xml